name: Build App - Main

env:
  PROJECT_PATH: src/workshop-app
  OCTOPUS_SPACE: ${{ secrets.OCTOPUS_DEFAULT_SPACENAME }}
on:
  workflow_dispatch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set version
      run: echo "PACKAGE_VERSION=$(date +'%Y.%-m.%-d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore $PROJECT_PATH
    - name: Build
      run: dotnet build --no-restore --configuration Release $PROJECT_PATH
    - name: Create artifacts folder
      run: |
        mkdir "$GITHUB_WORKSPACE/artifacts"
    - name: Create App Package
      run: dotnet pack --no-build --configuration Release --output "$GITHUB_WORKSPACE/artifacts" /p:Version=${{ env.PACKAGE_VERSION }} $PROJECT_PATH
    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.8
      with:
        version: latest
    - name: Push Sample App Package
      uses: OctopusDeploy/push-package-action@v1.1.1
      with:
        api_key: ${{ secrets.OCTOPUS_API_KEY }}
        server: ${{ secrets.OCTOPUS_SERVER_URL }}
        packages: "artifacts/workshop-app.${{ env.PACKAGE_VERSION }}.nupkg"
        space: ${{ env.$OCTOPUS_SPACE }}
